export const projectPage = {
  button: {
    addNewProject: '.tw-new-project-button-box.ax-new-project-button-box',
    chooseTemplate: 'button[type="button"] >> text="Next: Choose a template"',
    createProject: 'button[type="button"] >> text="Create Project"',
    createTaskList: '[data-l10n-key="projects.buttons.create_new_tasklist"]',
    addNewTask: '.ax-tasklist-header__add-icon[role="button"]',
    createNewTask: '[data-l10n-key="tasks.buttons.create"]',
    closePanel: '.ax-floating-panel-desktop__close-button',
    addProperties: '[data-name="add"]',
    pickRangeYear: '.ax-calendar-picker__jump',
    selectYear: '.tw-calendar-picker__year',
    selectMonth: '.tw-calendar-picker__month',
    selectDate: '.ax-calendar-picker__date.--weekday.--this-month',
    selectHour: '.ax-time-input__hour',
    selectMinute: '.ax-time-input__minute',
    addDateTimePicker: '[data-l10n-key="input_widget.date_picker.button.add"]',
    addAttachemnt: '[data-l10n-key="attachment.button.label"]',
  },
  panel: {
    newProject: '[data-l10n-key="project.new_project_modal.new_project"]',
    template: '[data-l10n-key="project.choose_workflow_modal.choose_workflow"]',
    taskDetail: '.tw-editable-panel-title__text',
    commentSection: '.tw-message-body',
    setDate: '[data-l10n-key="tasks.properties.set_date"]',
  },
  textbox: {
    projectName: '[name="project-name"]',
    projectDescription: 'input[name="description"]',
    projectTitle: '.ax-project-header__title',
    preCreateTaskListName: '.ax-pre-created-tasklist',
    taskListName: '.ax-editable-text-field',
    addTaskName: '.ax-task-or-note-input-panel__input-box',
  },
  label: {
    taskTitle: '.ax-task-header__title',
    commentHeader: '[data-l10n-key="tasks.headers.comments_only"]',
    propertiesHeader: '[data-l10n-key="tasks.headers.properties"]',
    dueDateRow: '.ax-task-date-row',
    dueDateValue: '[data-l10n-key="tasks.properties.due_date2"]',
    fileHeader: '[data-l10n-key="tasks.properties.tab.title.resources.count"]',
    fileName: '.ax-file-name-cell__name',
  }
} as const
